# Kivy Buildozer Android CI
name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Date
        shell: bash
        run: |
          echo "date=$(date +'%Y-%m-%d--%H-%M')" >> $GITHUB_OUTPUT
        id: get-date

      - name: Build with Buildozer
        uses: kivy/buildozer-action@v1.2.3
        id: buildozer
        with:
          workdir: .
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AI-Vision-Guide-${{ steps.get-date.outputs.date }}
          path: bin/*.apk
